url: http://localhost:3000
keys:
  configdb: ch4nge_me_for_Pr0duction!!!@@362184689g

server:
  port: 3000
  proxy: false

oidc:
  clients:
    - client_id: foo
      client_secret: bar
      redirect_uris:
      - http://192.168.1.21:8090/headers
